FROM eclipse-temurin:17-jre
WORKDIR /app
COPY target/*.jar app.jar
RUN groupadd --system app && useradd --system --gid app --uid 10001 --home-dir /nonexistent --no-create-home app \
    && mkdir -p /tmp /app && chown -R 10001:10001 /app /tmp
USER 10001:10001
EXPOSE 8080 8443
ENTRYPOINT ["java","-Djava.io.tmpdir=/tmp","-jar","/app/app.jar"]
